import type { Metadata } from "next";
import { Inter, Roboto_Mono, Space_Mono } from "next/font/google";
import "../globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import MainLayoutHeader from "../_components/main-layout-header";
import { twJoin } from "tailwind-merge";

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});

const space_mono = Space_Mono({
  subsets: ["latin"],
  variable: "--font-space-mono",
  display: "swap",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twJoin(roboto_mono.className, space_mono.className)}
        suppressHydrationWarning={true}
      >
        <AntdRegistry>
          <MainLayoutHeader />
          <div
            className={twJoin(
              "font-roboto_mono",
              "flex justify-center",
              "min-h-[calc(100svh-80px)]",
              "relative w-screen mt-20"
            )}
          >
            {children}
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
