name: Deploy develop crawl-data
run-name: ${{ github.actor }} is deploying develop branch🚀
on:
  push:
    branches:
      - "develop"
jobs:
  Deploy:
    runs-on: [self-hosted, ai-minting-fe-deploy]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18.19
        uses: actions/setup-node@v2
        with:
          node-version: 18.19
      - run: |
          echo "${{ vars.ENV_AI_MINTING }}" >> .env.production
          yarn
          yarn build
          pm2 restart pm2.json
